// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Nutcracker_V1

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_headerPanel;
extern lv_obj_t * ui_headerLabel;
extern lv_obj_t * ui_resultPanel;
extern lv_obj_t * ui_resultLabel;
extern lv_obj_t * ui_batchResult;
extern lv_obj_t * ui_categoryPanel;
extern lv_obj_t * ui_apiPanel;
extern lv_obj_t * ui_apiPanelLabel;
extern lv_obj_t * ui_apiPercentageValueLabel;
extern lv_obj_t * ui_apiPercentageSymbolLabel;
extern lv_obj_t * ui_secondsPanel;
extern lv_obj_t * ui_secondsPanelLabel;
extern lv_obj_t * ui_secondsPercentageValueLabel;
extern lv_obj_t * ui_secondsPercentageSymbolLabel;
extern lv_obj_t * ui_rashiPanel;
extern lv_obj_t * ui_rashiPanelLabel;
extern lv_obj_t * ui_rashiPercentageValueLabel;
extern lv_obj_t * ui_secondsPercentageSymbolLabel2;
extern lv_obj_t * ui_mangalaPanel;
extern lv_obj_t * ui_mangalaPanelLabel;
extern lv_obj_t * ui_mangalaPercentageValueLabel;
extern lv_obj_t * ui_secondsPercentageSymbolLabel1;
extern lv_obj_t * ui_Button;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_headerPanel;
extern lv_obj_t * uic_headerLabel;
extern lv_obj_t * uic_resultPanel;
extern lv_obj_t * uic_resultLabel;
extern lv_obj_t * uic_batchResult;
extern lv_obj_t * uic_categoryPanel;
extern lv_obj_t * uic_apiPanel;
extern lv_obj_t * uic_apiPanelLabel;
extern lv_obj_t * uic_apiPercentageValueLabel;
extern lv_obj_t * uic_apiPercentageSymbolLabel;
extern lv_obj_t * uic_secondsPanel;
extern lv_obj_t * uic_secondsPanelLabel;
extern lv_obj_t * uic_secondsPercentageValueLabel;
extern lv_obj_t * uic_secondsPercentageSymbolLabel;
extern lv_obj_t * uic_rashiPanel;
extern lv_obj_t * uic_rashiPanelLabel;
extern lv_obj_t * uic_rashiPercentageValueLabel;
extern lv_obj_t * uic_secondsPercentageSymbolLabel2;
extern lv_obj_t * uic_mangalaPanel;
extern lv_obj_t * uic_mangalaPanelLabel;
extern lv_obj_t * uic_mangalaPercentageValueLabel;
extern lv_obj_t * uic_secondsPercentageSymbolLabel1;
extern lv_obj_t * uic_Button;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

