// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Nutcracker_V1

#include "ui.h"

lv_obj_t * uic_Button;
lv_obj_t * uic_secondsPercentageSymbolLabel1;
lv_obj_t * uic_mangalaPercentageValueLabel;
lv_obj_t * uic_mangalaPanelLabel;
lv_obj_t * uic_mangalaPanel;
lv_obj_t * uic_secondsPercentageSymbolLabel2;
lv_obj_t * uic_rashiPercentageValueLabel;
lv_obj_t * uic_rashiPanelLabel;
lv_obj_t * uic_rashiPanel;
lv_obj_t * uic_secondsPercentageSymbolLabel;
lv_obj_t * uic_secondsPercentageValueLabel;
lv_obj_t * uic_secondsPanelLabel;
lv_obj_t * uic_secondsPanel;
lv_obj_t * uic_apiPercentageSymbolLabel;
lv_obj_t * uic_apiPercentageValueLabel;
lv_obj_t * uic_apiPanelLabel;
lv_obj_t * uic_apiPanel;
lv_obj_t * uic_categoryPanel;
lv_obj_t * uic_batchResult;
lv_obj_t * uic_resultLabel;
lv_obj_t * uic_resultPanel;
lv_obj_t * uic_headerLabel;
lv_obj_t * uic_headerPanel;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_headerPanel = NULL;
lv_obj_t * ui_headerLabel = NULL;
lv_obj_t * ui_resultPanel = NULL;
lv_obj_t * ui_resultLabel = NULL;
lv_obj_t * ui_batchResult = NULL;
lv_obj_t * ui_categoryPanel = NULL;
lv_obj_t * ui_apiPanel = NULL;
lv_obj_t * ui_apiPanelLabel = NULL;
lv_obj_t * ui_apiPercentageValueLabel = NULL;
lv_obj_t * ui_apiPercentageSymbolLabel = NULL;
lv_obj_t * ui_secondsPanel = NULL;
lv_obj_t * ui_secondsPanelLabel = NULL;
lv_obj_t * ui_secondsPercentageValueLabel = NULL;
lv_obj_t * ui_secondsPercentageSymbolLabel = NULL;
lv_obj_t * ui_rashiPanel = NULL;
lv_obj_t * ui_rashiPanelLabel = NULL;
lv_obj_t * ui_rashiPercentageValueLabel = NULL;
lv_obj_t * ui_secondsPercentageSymbolLabel2 = NULL;
lv_obj_t * ui_mangalaPanel = NULL;
lv_obj_t * ui_mangalaPanelLabel = NULL;
lv_obj_t * ui_mangalaPercentageValueLabel = NULL;
lv_obj_t * ui_secondsPercentageSymbolLabel1 = NULL;
lv_obj_t * ui_Button = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_headerPanel, 230);
    lv_obj_set_height(ui_headerPanel, 50);
    lv_obj_set_x(ui_headerPanel, 0);
    lv_obj_set_y(ui_headerPanel, 5);
    lv_obj_set_align(ui_headerPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_headerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_headerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_headerPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_headerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_headerPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_headerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_headerPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_headerPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_headerPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_headerPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_headerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_headerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_headerPanel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_headerPanel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerLabel = lv_label_create(ui_headerPanel);
    lv_obj_set_width(ui_headerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_headerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_headerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_headerLabel, "Areca Classifier");
    lv_obj_set_style_text_color(ui_headerLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_headerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_headerLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resultPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_resultPanel, 230);
    lv_obj_set_height(ui_resultPanel, 50);
    lv_obj_set_x(ui_resultPanel, 0);
    lv_obj_set_y(ui_resultPanel, 56);
    lv_obj_set_align(ui_resultPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_resultPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_resultPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_resultPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resultPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_resultPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_resultPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_resultPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resultLabel = lv_label_create(ui_resultPanel);
    lv_obj_set_width(ui_resultLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resultLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_resultLabel, -10);
    lv_obj_set_y(ui_resultLabel, 0);
    lv_obj_set_align(ui_resultLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_resultLabel, "Batch Result");
    lv_obj_set_style_text_color(ui_resultLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_resultLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_resultLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_resultLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batchResult = lv_label_create(ui_resultPanel);
    lv_obj_set_width(ui_batchResult, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batchResult, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batchResult, 5);
    lv_obj_set_y(ui_batchResult, 0);
    lv_obj_set_align(ui_batchResult, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_batchResult, "");
    lv_obj_set_style_text_color(ui_batchResult, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batchResult, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_batchResult, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batchResult, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_categoryPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_categoryPanel, 230);
    lv_obj_set_height(ui_categoryPanel, 203);
    lv_obj_set_x(ui_categoryPanel, 0);
    lv_obj_set_y(ui_categoryPanel, 110);
    lv_obj_set_align(ui_categoryPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_categoryPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_categoryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_categoryPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_categoryPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_categoryPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_categoryPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_categoryPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apiPanel = lv_obj_create(ui_categoryPanel);
    lv_obj_set_width(ui_apiPanel, 105);
    lv_obj_set_height(ui_apiPanel, 95);
    lv_obj_set_x(ui_apiPanel, -55);
    lv_obj_set_y(ui_apiPanel, -10);
    lv_obj_set_align(ui_apiPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_apiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_apiPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apiPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_apiPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_apiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_apiPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apiPanelLabel = lv_label_create(ui_apiPanel);
    lv_obj_set_width(ui_apiPanelLabel, lv_pct(135));
    lv_obj_set_height(ui_apiPanelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_apiPanelLabel, 0);
    lv_obj_set_y(ui_apiPanelLabel, -13);
    lv_obj_set_align(ui_apiPanelLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_apiPanelLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_apiPanelLabel, "Api");
    lv_obj_set_style_text_color(ui_apiPanelLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_apiPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_apiPanelLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_apiPanelLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_apiPanelLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apiPanelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apiPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_apiPanelLabel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_apiPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_apiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_apiPanelLabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_apiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_apiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_apiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_apiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apiPercentageValueLabel = lv_label_create(ui_apiPanel);
    lv_obj_set_width(ui_apiPercentageValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_apiPercentageValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_apiPercentageValueLabel, -15);
    lv_obj_set_y(ui_apiPercentageValueLabel, 10);
    lv_obj_set_align(ui_apiPercentageValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_apiPercentageValueLabel, "");
    lv_obj_set_style_text_color(ui_apiPercentageValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_apiPercentageValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_apiPercentageValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_apiPercentageValueLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apiPercentageSymbolLabel = lv_label_create(ui_apiPanel);
    lv_obj_set_width(ui_apiPercentageSymbolLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_apiPercentageSymbolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_apiPercentageSymbolLabel, 5);
    lv_obj_set_y(ui_apiPercentageSymbolLabel, 10);
    lv_obj_set_align(ui_apiPercentageSymbolLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_apiPercentageSymbolLabel, "%");
    lv_obj_set_style_text_color(ui_apiPercentageSymbolLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_apiPercentageSymbolLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_apiPercentageSymbolLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondsPanel = lv_obj_create(ui_categoryPanel);
    lv_obj_set_width(ui_secondsPanel, 105);
    lv_obj_set_height(ui_secondsPanel, 95);
    lv_obj_set_x(ui_secondsPanel, 55);
    lv_obj_set_y(ui_secondsPanel, -10);
    lv_obj_set_align(ui_secondsPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_secondsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_secondsPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_secondsPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_secondsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_secondsPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_secondsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_secondsPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondsPanelLabel = lv_label_create(ui_secondsPanel);
    lv_obj_set_width(ui_secondsPanelLabel, lv_pct(135));
    lv_obj_set_height(ui_secondsPanelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondsPanelLabel, 0);
    lv_obj_set_y(ui_secondsPanelLabel, -13);
    lv_obj_set_align(ui_secondsPanelLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_secondsPanelLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_secondsPanelLabel, "Seconds");
    lv_obj_set_style_text_color(ui_secondsPanelLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondsPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_secondsPanelLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondsPanelLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_secondsPanelLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_secondsPanelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_secondsPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_secondsPanelLabel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_secondsPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_secondsPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_secondsPanelLabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_secondsPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_secondsPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_secondsPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_secondsPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondsPercentageValueLabel = lv_label_create(ui_secondsPanel);
    lv_obj_set_width(ui_secondsPercentageValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondsPercentageValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondsPercentageValueLabel, -15);
    lv_obj_set_y(ui_secondsPercentageValueLabel, 10);
    lv_obj_set_align(ui_secondsPercentageValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secondsPercentageValueLabel, "");
    lv_obj_set_style_text_color(ui_secondsPercentageValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondsPercentageValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_secondsPercentageValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondsPercentageValueLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondsPercentageSymbolLabel = lv_label_create(ui_secondsPanel);
    lv_obj_set_width(ui_secondsPercentageSymbolLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondsPercentageSymbolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondsPercentageSymbolLabel, 5);
    lv_obj_set_y(ui_secondsPercentageSymbolLabel, 10);
    lv_obj_set_align(ui_secondsPercentageSymbolLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_secondsPercentageSymbolLabel, "%");
    lv_obj_set_style_text_color(ui_secondsPercentageSymbolLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondsPercentageSymbolLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondsPercentageSymbolLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rashiPanel = lv_obj_create(ui_categoryPanel);
    lv_obj_set_width(ui_rashiPanel, 105);
    lv_obj_set_height(ui_rashiPanel, 95);
    lv_obj_set_x(ui_rashiPanel, 55);
    lv_obj_set_y(ui_rashiPanel, 88);
    lv_obj_set_align(ui_rashiPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_rashiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rashiPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rashiPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rashiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rashiPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rashiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rashiPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rashiPanelLabel = lv_label_create(ui_rashiPanel);
    lv_obj_set_width(ui_rashiPanelLabel, lv_pct(135));
    lv_obj_set_height(ui_rashiPanelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rashiPanelLabel, 0);
    lv_obj_set_y(ui_rashiPanelLabel, -13);
    lv_obj_set_align(ui_rashiPanelLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_rashiPanelLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_rashiPanelLabel, "Rashi");
    lv_obj_set_style_text_color(ui_rashiPanelLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rashiPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rashiPanelLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rashiPanelLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rashiPanelLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rashiPanelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rashiPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rashiPanelLabel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rashiPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rashiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rashiPanelLabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rashiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rashiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rashiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rashiPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rashiPercentageValueLabel = lv_label_create(ui_rashiPanel);
    lv_obj_set_width(ui_rashiPercentageValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rashiPercentageValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rashiPercentageValueLabel, -15);
    lv_obj_set_y(ui_rashiPercentageValueLabel, 10);
    lv_obj_set_align(ui_rashiPercentageValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rashiPercentageValueLabel, "");
    lv_obj_set_style_text_color(ui_rashiPercentageValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rashiPercentageValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rashiPercentageValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rashiPercentageValueLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondsPercentageSymbolLabel2 = lv_label_create(ui_rashiPanel);
    lv_obj_set_width(ui_secondsPercentageSymbolLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondsPercentageSymbolLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondsPercentageSymbolLabel2, 5);
    lv_obj_set_y(ui_secondsPercentageSymbolLabel2, 10);
    lv_obj_set_align(ui_secondsPercentageSymbolLabel2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_secondsPercentageSymbolLabel2, "%");
    lv_obj_set_style_text_color(ui_secondsPercentageSymbolLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondsPercentageSymbolLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondsPercentageSymbolLabel2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mangalaPanel = lv_obj_create(ui_categoryPanel);
    lv_obj_set_width(ui_mangalaPanel, 105);
    lv_obj_set_height(ui_mangalaPanel, 95);
    lv_obj_set_x(ui_mangalaPanel, -55);
    lv_obj_set_y(ui_mangalaPanel, 88);
    lv_obj_set_align(ui_mangalaPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_mangalaPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mangalaPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mangalaPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mangalaPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mangalaPanel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mangalaPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mangalaPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mangalaPanelLabel = lv_label_create(ui_mangalaPanel);
    lv_obj_set_width(ui_mangalaPanelLabel, lv_pct(135));
    lv_obj_set_height(ui_mangalaPanelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mangalaPanelLabel, 0);
    lv_obj_set_y(ui_mangalaPanelLabel, -13);
    lv_obj_set_align(ui_mangalaPanelLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_mangalaPanelLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_mangalaPanelLabel, "Mangala");
    lv_obj_set_style_text_color(ui_mangalaPanelLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mangalaPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mangalaPanelLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mangalaPanelLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_mangalaPanelLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mangalaPanelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mangalaPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mangalaPanelLabel, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mangalaPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mangalaPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_mangalaPanelLabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_mangalaPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_mangalaPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_mangalaPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_mangalaPanelLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mangalaPercentageValueLabel = lv_label_create(ui_mangalaPanel);
    lv_obj_set_width(ui_mangalaPercentageValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mangalaPercentageValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mangalaPercentageValueLabel, -15);
    lv_obj_set_y(ui_mangalaPercentageValueLabel, 10);
    lv_obj_set_align(ui_mangalaPercentageValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mangalaPercentageValueLabel, "");
    lv_obj_set_style_text_color(ui_mangalaPercentageValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mangalaPercentageValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mangalaPercentageValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mangalaPercentageValueLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secondsPercentageSymbolLabel1 = lv_label_create(ui_mangalaPanel);
    lv_obj_set_width(ui_secondsPercentageSymbolLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secondsPercentageSymbolLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secondsPercentageSymbolLabel1, 5);
    lv_obj_set_y(ui_secondsPercentageSymbolLabel1, 10);
    lv_obj_set_align(ui_secondsPercentageSymbolLabel1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_secondsPercentageSymbolLabel1, "%");
    lv_obj_set_style_text_color(ui_secondsPercentageSymbolLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secondsPercentageSymbolLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secondsPercentageSymbolLabel1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button, lv_pct(100));
    lv_obj_set_height(ui_Button, lv_pct(100));
    lv_obj_set_align(ui_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen1 = ui_Screen1;
    uic_headerPanel = ui_headerPanel;
    uic_headerLabel = ui_headerLabel;
    uic_resultPanel = ui_resultPanel;
    uic_resultLabel = ui_resultLabel;
    uic_batchResult = ui_batchResult;
    uic_categoryPanel = ui_categoryPanel;
    uic_apiPanel = ui_apiPanel;
    uic_apiPanelLabel = ui_apiPanelLabel;
    uic_apiPercentageValueLabel = ui_apiPercentageValueLabel;
    uic_apiPercentageSymbolLabel = ui_apiPercentageSymbolLabel;
    uic_secondsPanel = ui_secondsPanel;
    uic_secondsPanelLabel = ui_secondsPanelLabel;
    uic_secondsPercentageValueLabel = ui_secondsPercentageValueLabel;
    uic_secondsPercentageSymbolLabel = ui_secondsPercentageSymbolLabel;
    uic_rashiPanel = ui_rashiPanel;
    uic_rashiPanelLabel = ui_rashiPanelLabel;
    uic_rashiPercentageValueLabel = ui_rashiPercentageValueLabel;
    uic_secondsPercentageSymbolLabel2 = ui_secondsPercentageSymbolLabel2;
    uic_mangalaPanel = ui_mangalaPanel;
    uic_mangalaPanelLabel = ui_mangalaPanelLabel;
    uic_mangalaPercentageValueLabel = ui_mangalaPercentageValueLabel;
    uic_secondsPercentageSymbolLabel1 = ui_secondsPercentageSymbolLabel1;
    uic_Button = ui_Button;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    uic_headerPanel = NULL;
    ui_headerPanel = NULL;
    uic_headerLabel = NULL;
    ui_headerLabel = NULL;
    uic_resultPanel = NULL;
    ui_resultPanel = NULL;
    uic_resultLabel = NULL;
    ui_resultLabel = NULL;
    uic_batchResult = NULL;
    ui_batchResult = NULL;
    uic_categoryPanel = NULL;
    ui_categoryPanel = NULL;
    uic_apiPanel = NULL;
    ui_apiPanel = NULL;
    uic_apiPanelLabel = NULL;
    ui_apiPanelLabel = NULL;
    uic_apiPercentageValueLabel = NULL;
    ui_apiPercentageValueLabel = NULL;
    uic_apiPercentageSymbolLabel = NULL;
    ui_apiPercentageSymbolLabel = NULL;
    uic_secondsPanel = NULL;
    ui_secondsPanel = NULL;
    uic_secondsPanelLabel = NULL;
    ui_secondsPanelLabel = NULL;
    uic_secondsPercentageValueLabel = NULL;
    ui_secondsPercentageValueLabel = NULL;
    uic_secondsPercentageSymbolLabel = NULL;
    ui_secondsPercentageSymbolLabel = NULL;
    uic_rashiPanel = NULL;
    ui_rashiPanel = NULL;
    uic_rashiPanelLabel = NULL;
    ui_rashiPanelLabel = NULL;
    uic_rashiPercentageValueLabel = NULL;
    ui_rashiPercentageValueLabel = NULL;
    uic_secondsPercentageSymbolLabel2 = NULL;
    ui_secondsPercentageSymbolLabel2 = NULL;
    uic_mangalaPanel = NULL;
    ui_mangalaPanel = NULL;
    uic_mangalaPanelLabel = NULL;
    ui_mangalaPanelLabel = NULL;
    uic_mangalaPercentageValueLabel = NULL;
    ui_mangalaPercentageValueLabel = NULL;
    uic_secondsPercentageSymbolLabel1 = NULL;
    ui_secondsPercentageSymbolLabel1 = NULL;
    uic_Button = NULL;
    ui_Button = NULL;

}
